### ISSUE TITLE
Configure the app to be brought up with docker-compose

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#103]
Currently, the application can only be brought up via `docker` commands. It would be nice to bring it up simply with `docker-compose up`.

**Comment by JasonSarwar** [comment]
Can I work on this?

**Comment by Jaspaul** [comment]
@JasonSarwar Just saw your comment now. My apologies I should have posted here before I started working on this.

@Asuza the attached PR should allow you to bring up this project with `docker-compose up`

**Comment by JasonSarwar** [comment]
@Jaspaul No problem!
