### ISSUE TITLE
Problem logging-in

### ISSUE THREAD

**Issue by slugo** [JSJitsu/ai-battle-website#22]
Is the website ready to be used ? I forked the `hero-starter` repository so I could participate but then when I tried to log in with github at `jsfight.club`, I entered my credentials and then page just keeps loading until eventually I get a `504 Gateway Time-out` error.

On another note, seems like you can access an unsecured version of the website at `http://jsfight.club/` that maybe should be redirected to `https://jsfight.club/` ?

**Comment by Asuza** [comment]
@slugo thanks for pointing that out! I apparently haven't tried logging in as a new user after I merged the website repo and game-runner repo together.

I have pushed a fix live to address the issue. Please re-open this issue if you have any more problems.

**Comment by Asuza** [comment]
Regarding the redirect, you are correct. It's just something I haven't gotten to yet.

**Comment by slugo** [comment]
@Asuza Oh ok, I just found the project and really liked it so wanted to test it out. Also, don't know if it's related but after your fix I managed to log in, but when trying to look at my stats and settings I kept getting some errors when changing tabs and now the website is entirely unreachable.

**Comment by Asuza** [comment]
Hey @slugo, I see that you got some errors and will fix that problem asap. There's nothing obviously wrong with the site that would cause it to be down, so I'm looking into that issue as well.

**Comment by Asuza** [comment]
@slugo, the website is online and you should be able to log in just fine now, but it is still a work in progress until we release it officially. Thanks for breaking some things!
