### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by slugo** [JSJitsu/ai-battle-website#24]
I'm trying to get the application started but I'm getting `Error: Cannot find module '../secrets'`, I guess that's related to the database, so I guess there's something else that needs to be done aside from installing npm and bower dependencies?

**Comment by Asuza** [comment]
@slugo you are correct. I've moved a lot of things around since starting on this project, and didn't realize the file was missing.

If you look in the *gamerunner* folder there is a *[secrets-template.js](https://github.com/JSJitsu/ai-battle-website/blob/master/gamerunner/secrets-template.js)* file that you can copy to be your *secrets.js*. You should be able to follow the instructions within that file, but I haven't looked at it in a while.

Let me know if you have any more difficulties.

**Comment by Asuza** [comment]
I created #27 to help address this issue.

**Comment by slugo** [comment]
Thanks, I used `secrets-template.js` to create the `secrets.js` file and entered the required information after creating the local database and registering the app on github for authentication. However, as I don't have the database configured correctly with all it's tables and such, I'm still getting some errors getting the server started, the first one being `error: relation "session" does not exist`.

**Comment by Asuza** [comment]
@slugo, the last step should be to add the session table. It should be as simple as running the following command:
```
psql jsfightclub < ./node_modules/connect-pg-simple/table.sql
```

**Comment by slugo** [comment]
Ok, I created the table and the server managed to start, but I also need to create the other ones. After trying to log in I got `error: relation "player" does not exist` and there must be others. How do you suggest to go on about the database config ?

**Comment by Asuza** [comment]
@slugo, there is a node script, I think in the *gamerunner/database* folder that you can run to set up the rest of the tables. Let me know if it gives you any trouble.

**Comment by slugo** [comment]
@Asuza thanks, I used `game_runner/database/initialize.js` to create the tables. Although the `game_results` one threw `error: relation "game" does not exist` so I had to create it manually after the script, but everything seems to be fine now :smiley: .

**Comment by Asuza** [comment]
@slugo if you are planning on fixing #27, please let me know. Otherwise, I'd like to update it soon to be more current in case anyone else wants to contribute.

**Comment by slugo** [comment]
Oh right, yes I will update with some info when I get home.

**Comment by Asuza** [comment]
Cool, thanks!

**Comment by Asuza** [comment]
Closing this with the recent enhancements to the readme and other helpful code additions.
