### ISSUE TITLE
Update the battle roster to show the same badge that's on the field

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#26]
If you look at a battle on [the website](https://jsfight.club), you can see that in the list of active players, it shows `(id:3)` instead of the nicer square badge that's on the battlefield.

Update the battle roster to show the square badge instead of the "id" text.

**Comment by tenshi13** [comment]
Hey @Asuza, trying to explore a bit more of the jsjitsu projects, i'd like to give this a go also if its cool?

**Comment by Asuza** [comment]
Sure! You might need to reference #24 to get things up and running.

**Comment by tenshi13** [comment]
wew, yep I just saw #24 and #27... I might comment a bit on #27 if I've got some ideas about it

**Comment by tenshi13** [comment]
PR : https://github.com/JSJitsu/ai-battle-website/pull/35

**Comment by Asuza** [comment]
Fixed by #35
