### ISSUE TITLE
Improve instructions to get the server up and running

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#27]
The readme does not accurately describe how to get the website set up. Improve the instructions so it's easier to get started. See #24 for some information on missing documentation.

Don't worry about improving the process to get it up and running in this issue, but if part of getting set up is convoluted, please discuss it here and we can create new issues as needed.

**Comment by slugo** [comment]
Ok, so this were the steps I followed to get the website up and running:

1. Clone repository and install dependencies with `npm install` and `bower install`.
2. Install `postgresql` and create a database and user to be used by the website, I did it manually, but then found out there was a script for doing this at `gamerunner/database/setup-postgres.sh` that executed the same commands I did so running the script should work.
3. Register the website as an OAuth Application [here](https://github.com/settings/developers). Then copy `gamerunner/secrets-template.js` to the project root directory and rename it to `secrets.js`, as the db connect script (`database/connect.js`) is looking for it there. After that you should fill the fields of the `secrets.js` file with your application's info:
   * `secrets.postgresUrl` should be your db connection string, with the following syntax: `postgresql://${dbUser}:${dbUserPassword}@${hostname}/${dbName}`
   * `secrets.appKey` is your Client Id and `secrets.appSecret` is your Client Secret that are given to you after registering the app as an OAuth application. Also added a key named `callbackUrl` for further use.
4. Go into the `server.js` file at the root directory and see that the info inside the `options` object is being filled by passing values to the command line, you can do it like this, but I required the `secrets.js` file and changed it to something like 
```js
github: {
        clientId: secrets.appKey,
        clientSecret: secrets.appSecret,
        callbackUrl: secrets.callbackUrl,
    }
```
5. Last step is creating the database tables, to do this first run `psql jsfightclub < ./node_modules/connect-pg-simple/table.sql` and then `gamerunner/database/initialize.js` and you should be ready to go.

**Comment by Asuza** [comment]
That's way too complicated! One more thing to fix, I suppose.

**Comment by tenshi13** [comment]
some minor suggestion:
- some tutorial/instruction to run the server with --no-github, by running the gamerunner/run-test-game.js
- Grunt -> saw that the project is still using grunt-contrib-sass (requires ruby, if im not wrong), from past projects it was suggested to use grunt-sass(node lib-sass) instead, it's faster and doesn't need ruby

**Comment by Asuza** [comment]
@tenshi13 I'll keep that in mind, regarding sass. I'd like to get rid of grunt entirely and switch to gulp or something else, someday.
