### ISSUE TITLE
Center team members caption overlay

### ISSUE THREAD

**Issue by slugo** [JSJitsu/ai-battle-website#29]
Right now when you hover over a team member image, you get caption overlay that doesn't appears to be centered. Is this intended ?

![screenshot from 2016-10-22 12-16-26](https://cloud.githubusercontent.com/assets/15680836/19620754/8ed7192c-9851-11e6-8e69-9d25c28f88f2.png)

**Comment by Asuza** [comment]
No, it broke when I was fixing a layout issue. It's supposed to be centered.

**Comment by slugo** [comment]
Can I submit a fix for that then ?

**Comment by Asuza** [comment]
Of course!

**Comment by slugo** [comment]
Ok, it also seems that `public/css/main.css` doesn't have all the latest css changes, when I compiled the scss files on `public/scss/` I got some more changes in `main.css` apart from the one I did. Should I only commit my changes to `_meetTeam.scss` ?

**Comment by Asuza** [comment]
Yes, that's fine. I need to remove the built files and add them to the *.gitignore* file at some point.
