### ISSUE TITLE
Wrong team being shown as the winner

### ISSUE THREAD

**Issue by slugo** [JSJitsu/ai-battle-website#31]
In the current game that is being showed in the [website](https://jsfight.club/), the winner is being showed is the Blue Team, even though at the end of all the turns Red Team managed to stay with one member alive and has more diamonds than the blue team.

![image](https://cloud.githubusercontent.com/assets/15680836/19627657/c899adfa-9919-11e6-86d7-64657d133d35.png)

Looking at the code in [GameView.js](https://github.com/JSJitsu/ai-battle-website/blob/master/public/js/game/GameView.js), inside the `checkWinner` function red team is treated as team `0`, and blue team as team `1`. However, when running a test battle locally with [run-games.js](https://github.com/JSJitsu/ai-battle-website/blob/master/gamerunner/run-games.js), we can see where each member is assigned, and the number of the teams seem to be reversed. 

This bug is only visual, as the correct team is being registered as the winner in the database, but there's also another bug causing the wrong team to be selected as the winner. This is caused because even though one team kills the other team, when the winner is being selected in [game-engine.js](https://github.com/JSJitsu/ai-battle-website/blob/master/public/js/game-engine.js), the following code is always executed, resulting in the read team winning even if all of it's members are dead, and vice-versa. You can see that even if the game ends because of one team dying, the `Game over. Maximum number of turns reached` message is always printed in console.

```js
  //Exceeded maximum turns
  if (this.turn >= this.maxTurn) {
    console.log('Game over. Maximum number of turns reached.');
    this.ended = true;
    var teamDiamonds0 = this._teamDiamonds(this.teams[0]);
    var teamDiamonds1 = this._teamDiamonds(this.teams[1]);
    if (teamDiamonds1 > teamDiamonds0) {
      this.winningTeam = 1;
    } else {
      this.winningTeam = 0;
    }
```

**Comment by Asuza** [comment]
Good catch! This sounds like a straightforward fix. I definitely don't want the wrong winner showing up after the official release.
