### ISSUE TITLE
Incorrect average stats for user

### ISSUE THREAD

**Issue by slugo** [JSJitsu/ai-battle-website#33]
In the average stats tab, `Deaths`, `Damage Dealt`, `Mines Captured`, and `Graves Robbed`, are always shown as 0. You can see my user lifetime stats are displaying correctly, but average stats are not being displayed accordingly. 
![screenshot from 2016-10-24 20-27-34](https://cloud.githubusercontent.com/assets/15680836/19668891/ff72c00e-9a28-11e6-8712-4c201e475bdf.png)
![screenshot from 2016-10-24 20-27-18](https://cloud.githubusercontent.com/assets/15680836/19668890/fe64ea16-9a28-11e6-8187-8a31c70fe613.png)

**Comment by Asuza** [comment]
I got this partially fixed, but it's got way too many decimal places. I'm not going to close this until that gets fixed.

**Comment by Asuza** [comment]
Fixed it!
