### ISSUE TITLE
Convert the arguments utility to commander.js

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#34]
Recently, in the hero-starter repo, the CLI arguments library [commander.js](https://github.com/tj/commander.js) was introduced. Replace the existing argument library in this repo with commander.js to maintain consistency across the project.

**Comment by Asuza** [comment]
@tenshi13, if you would like to do this, please let me know. Otherwise, I'll worry about it later or add it to Hacktoberfest. Thanks!

**Comment by tenshi13** [comment]
@Asuza, hey man, I don't mind doing this, but am still trying to set up the website atm, will have a look at #26 before I get to this

**Comment by tenshi13** [comment]
@Asuza hey man real sorry for delays, I'm a bit under pump at work on a payment project... will get this done in a bit : P

**Comment by Asuza** [comment]
Thanks, @tenshi13! Not a problem at all. I know the feeling.

**Comment by tenshi13** [comment]
@Asuza sorry finally had some time to had a look, just learned that commander.js had some limitations... it does not support or condition for cli inputs, and the help message is not very flexible... can you please have a look at PR : https://github.com/JSJitsu/ai-battle-website/pull/44

**Comment by Asuza** [comment]
@tenshi13, thanks for the help! I will look at it as soon as I can. In the meantime, https://jsfight.club is officially launched, if you're interested. :smile:

**Comment by Asuza** [comment]
Not going to worry about this anymore.
