### ISSUE TITLE
Inconsistent Github user object property "github_login"

### ISSUE THREAD

**Issue by tenshi13** [JSJitsu/ai-battle-website#36]
@Asuza hey man, I believe I've found a small bug in one of the battle test runners:
ai-battle-website/gamerunner/run-test-game.js @ln 45

I believe the property name should be 'github_login' instead
currently if I run the run-test-game.js

it will spit out:
`Adding user: undefined to game 0, team 0`

can you please verify if this is correct?
I can do a PR for this after your confirmation

**Comment by Asuza** [comment]
After following the code path to the ai-battle-engine, the planAllGames method is referencing `github_login`, so I believe you are correct.

**Comment by tenshi13** [comment]
@Asuza did a PR : https://github.com/JSJitsu/ai-battle-website/pull/38

**Comment by Asuza** [comment]
Fixed by #38!
