### ISSUE TITLE
Clicking the 'page-top' link and then refreshing prevents game from loading.

### ISSUE THREAD

**Issue by davmillar** [JSJitsu/ai-battle-website#46]
When refreshing the page after clicking the heading link to scroll to the top, the game no longer loads. This seems to be because of the '#page-top' hash and how the site uses hashes to determine what game to display.

**Comment by natedsaint** [comment]
@Asuza recently made some changes to let you link to specific games, might have some context. I'll take a look when I get some time.

**Comment by Asuza** [comment]
Fixed via #59. Thanks, @aewens!
