### ISSUE TITLE
Missing AI

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#52]
The following players are missing AI: @schas002, @papkie, @indiescope, @leon-wbr, @jfh7j, @mateeyow, @TIIGRUS, @mdhalim, @ArgeSwarge, @kongxingagit, @vitalyavolyn, @rymanalu, @adminha, @kre8sions, @olek557, @bganicky, @gnud, @angrykoala, @Raisour, @a7madgamal, @rafaelangical, @htar, and @Asyst.

Please remember to fork the [hero-starter](https://github.com/JSJitsu/hero-starter) to partake in battle! If you no longer want to participate, please let me know. Thanks!

**Comment by schas002** [comment]
Oh, I forgot! I still had my sign up from a few days ago! Thanks for making me realise.

**Comment by Asuza** [comment]
This month, these players are missing AI: @a7madgamal, @adminha, @amirbagh75, @angrykoala, @Asyst, @bganicky, @gnud, @htar, @jfh7j, @kongxingagit, @kre8sions, @Lastrik, @leon-wbr, @mateeyow, @mdhalim, @olek557, @papkie, @rafaelangical, @Raisour, @rymanalu, @TIIGRUS, @vitalyavolyn

Please remember to fork the [hero-starter](https://github.com/JSJitsu/hero-starter) to partake in battle! If you no longer want to participate, please let me know. Thanks!

**Comment by angrykoala** [comment]
Hi @Asuza Sorry,  I won't be participating for now should I send you an email or something?

**Comment by jfh7j** [comment]
I won't be participating anymore.

**Comment by vitalyavolyn** [comment]
I won't be participating

**Comment by Asuza** [comment]
Players can now disable their account from their account page.
