### ISSUE TITLE
Site's certificated expired for https://jsfight.club/ 

### ISSUE THREAD

**Issue by bmbeverst** [JSJitsu/ai-battle-website#53]
Please fix your Let's Encrypt configuration.

**Comment by Asuza** [comment]
Thanks, I'll fix it as soon as I can. It was supposed to be automated...

**Comment by Asuza** [comment]
Forced renewal of the SSL certificate.

**Comment by dtfinch** [comment]
The latest cert expired last night.

**Comment by Asuza** [comment]
Not sure what's up. I ran the command to update it before I went to bed. I'll look into it ASAP.

**Comment by Asuza** [comment]
Fixed. Thanks, @dtfinch.
