### ISSUE TITLE
Log In button doesn't update with the user's name in Firefox

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#55]
Steps to reproduce:
1. Click "Log in with GitHub"
2. Connect your GitHub account to the site, if necessary.
3. The button still shows "Log in with GitHub" instead of the username of the person logged in.

The user settings loads, so the problem seems to be specific to the log in button.

Tested in [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) 57.0b3.

**Comment by vikasmahato** [comment]
I would like to work on this bug. Can you assign it to me?

**Comment by Asuza** [comment]
By all means, it's yours. I'll have to see if I can actually mark you as the issue assignee. Right now it only lets me add JSJitsu members.

For comparison, this bug doesn't happen in Chrome. It shows the user name as expected.

**Comment by Asuza** [comment]
No longer an issue due to the rewrite in the _riotjs_ branch.
