### ISSUE TITLE
Player accounts should be disabled when we can't get their hero code

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#56]
Hero code is retrieved daily via the script: _./gamerunner/user_code/get-user-code-from-github.js_

Occasionally, we're unable to retrieve hero code. After adding necessary columns to the player database table, track the number of times a failure has occurred and then mark the account as disabled* after the 3rd failure.

Once the 3rd failure has occurred, include a disabled reason in the player record. The disabled reasons include:
- fetch _- unable to get any code_
- missing_hero _- unable to get the hero code_
- missing_helpers _- unable to get the helpers code_
- overweight _- file size of all code is unacceptable_
- hero_overweight _- file size of the hero code is unacceptable_
- helpers_overweight _- file size of the helpers code is unacceptable_

The failure count should only go up by 1 even if more than one error occurs in a given day (the script only runs once per day). This would give the user 3 days to fix any issues.

_*The account should be marked disabled but not really disabled. We can't truly disable it until the user has a way to re-enable their account._

**Comment by darrylpargeter** [comment]
Hey @Asuza would it be possible to give this one a go?

**Comment by Asuza** [comment]
Sure thing, @darrylpargeter.

**Comment by Asuza** [comment]
@darrylpargeter do you want to work on this anymore? Several things have changed since #63 was created.

**Comment by Asuza** [comment]
Fixed via #84, #85, #86, and #87.
