### ISSUE TITLE
Track fresh player statistics each month

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#57]
We currently have a `player_lifetime_stats` table. Add a new table called `player_monthly_stats` that stores the same information but is wiped clean on the first day of each month before that day's game begin.

Ensure that the stats are being populated into the new table and enhance the leaderboard route so the value of `:timePeriod` determines whether we get data from the lifetime table or the monthly table.

**Comment by ZackTaylor** [comment]
@Asuza I'd like to take a shot at this, but what files would I begin looking in to do so?

**Comment by Asuza** [comment]
You can see where the lifetime stats get saved here: https://github.com/JSJitsu/ai-battle-website/blob/7fe04da0f8879d7298d96b597dbcec5a5fdadf43/gamerunner/game_logic/GameRunner.js#L450. All of the stats are figured out in that same file.

In regards to the database, most of it's created in this file: https://github.com/JSJitsu/ai-battle-website/blob/master/database/initialize.js. Feel free to add database changes there for anyone building the database initially, but unfortunately once the changes go live I'll have to run a command on the database to make the change. I don't have anything in place to patch the database via a script.

**Comment by ZackTaylor** [comment]
Ok, ill work on this. ill let you know if I have any questions.

**Comment by Asuza** [comment]
Just FYI, the readme of this repo contains instructions on starting the vagrant machine. That should ease development pains.

**Comment by flesler** [comment]
The other option I see is to make the rankings based on ratios. So instead of total kills, kill ratio. Total wins -> win ratio. Much fairer to new players

**Comment by Asuza** [comment]
Closing this to create a new issue to use ratios for statistics.
