### ISSUE TITLE
User dropdown menu in navigation bar is not working

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#6]

**Comment by natedsaint** [comment]
I'm unable to figure out the issue here: it does work although it's floating strangely.

**Comment by Asuza** [comment]
It wouldn't do anything at all for me... I'll try it again as soon as i can.

**Comment by natedsaint** [comment]
Turned out to be caused by the dev files not all being properly included, so just use the build process (grunt watch now goes in about 3 seconds or so).
