### ISSUE TITLE
Add a simple database patching mechanism

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#65]
Currently, making database changes to the production site requires manual intervention. Create a way for the server to automatically apply patches (if needed) before the web server starts.

This change would be helpful when it's time for #56 and #57 to go live.

**Comment by jcfausto** [comment]
Hi @Asuza, I think I can handle that :-) Let me take a look at this and I'll get back to you soon with a proposal.

**Comment by Asuza** [comment]
I look forward to seeing it, @jcfausto.

**Comment by Asuza** [comment]
How's it going, @jcfausto?

**Comment by jcfausto** [comment]
Hi @Asuza, I'm on it. I hope to submit the PR by Sunday.

**Comment by Asuza** [comment]
Fixed by #68. And a lot of small refactors.
