### ISSUE TITLE
Add ability for the site to run via Docker/Rkt

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#67]
Allow the website to run in a container, either with [Docker](https://www.docker.com/) or [Rkt](https://coreos.com/rkt/). It would need to run Node JS and a Postgres database.

**Comment by jeromechrist** [comment]
Hello,

Willing to work on this, with Docker !

**Comment by Asuza** [comment]
Sounds good, @jeromechrist.

**Comment by BrainMaestro** [comment]
Is this still being worked on? I can pick it up if not.

**Comment by jeromechrist** [comment]
@BrainMaestro yes, I'm on it.

**Comment by Asuza** [comment]
Hey @jeromechrist, how's this going? I can't get Vagrant running on my local machine, so getting Docker running would be handy!

**Comment by jeromechrist** [comment]
@Asuza 

Hey, 

So this is what I've done : 

/!\ i had to comment out bower uglify or the app would not compile, it errors out at the minification of the browserified source of GameEngine /!\

- image is based off ubuntu:14.04

- it contains
      - postgresql 9.5
      - node 6
      - the repository (source) copied to /app
      - config-template.js copied to config.js
      - bootstrap-docker.sh which is the same as bootstrap.sh without the vagrant / dependencies stuff

how to build the image (current directory is the repo with the folder containing the Dockerfile) :

`docker build -t ai-battle-website .
`
 
how to run a container based off it : 

`docker run-it -p 8080:8080 ai-battle-website`

now  there are a certain number of manual steps as it was listed in the readme :

- start postgres : `service postgresql start`
- edit config.js user property : database.user set to 'vagrant'
- execute the db init script  : `node database/iniode database/initialize.js`
- under postgres user : `psql jsfightclub < ./node_modules/connect-pg-simple/table.sql`

I've then tested : `node gamerunner/run-test-game.js`
<details><summary>output : </summary>

> Setting up to run a test game. The results will be stored in the database.
> Planning games for 24 users.
> Adding user: Vaida to game 0, team 0
> Adding user: Eliwood to game 0, team 1
> Adding user: Sain to game 0, team 0
> Adding user: Rath to game 0, team 1
> Adding user: Lowen to game 0, team 0
> Adding user: Lucius to game 0, team 1
> Adding user: Farina to game 0, team 0
> Adding user: Marcus to game 0, team 1
> Adding user: Kent to game 0, team 0
> Adding user: Fiora to game 0, team 1
> Adding user: Lyn to game 0, team 0
> Adding user: Louise to game 0, team 1
> Adding user: Oswin to game 0, team 0
> Adding user: Florina to game 0, team 1
> Adding user: Wallace to game 0, team 0
> Adding user: Pent to game 0, team 1
> Adding user: Serra to game 0, team 0
> Adding user: Isadora to game 0, team 1
> Adding user: Erk to game 0, team 0
> Adding user: Heath to game 0, team 1
> Adding user: Nino to game 0, team 0
> Adding user: Rebecca to game 0, team 1
> Adding user: Wil to game 0, team 0
> Adding user: Hector to game 0, team 1
> Running game 0 at 2017-10-29T23:13:44.049Z
> Game over. Maximum number of turns reached.
> Playing game, turn 1250
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |   |   |H17|   |D00|D01|   |   |   |H15|   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |III|III|III|III|III|III|III|III|III|III|   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |   |   |   |H21|H01|   |   |   |   |   |   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |   |   |WWW|   |   |   |   |WWW|   |   |   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |   |   |   |III|   |   |III|   |H13|   |   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |D02|III|   |   |   |D03|D04|H23|   |   |III|D05|
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |D06|III|   |   |III|   |   |III|H05|   |III|D07|
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |   |   |WWW|   |   |   |   |WWW|   |   |   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |H16|   |   |   |   |   |   |   |   |   |   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |   |   |   |   |D08|D09|   |   |   |H22|   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |   |III|III|III|III|III|III|III|III|III|   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> |   |H10|   |   |   |D10|D11|   |   |   |   |   |
> |---|---|---|---|---|---|---|---|---|---|---|---|
> ********
> Saving game 0
> Updating all user stats...
>   Storing new statistics for Vaida
>   Storing new statistics for Eliwood
>   Storing new statistics for Sain
>   Storing new statistics for Rath
>   Storing new statistics for Lowen
>   Storing new statistics for Lucius
>   Storing new statistics for Farina
>   Storing new statistics for Marcus
>   Storing new statistics for Kent
>   Storing new statistics for Fiora
>   Storing new statistics for Lyn
>   Storing new statistics for Louise
>   Storing new statistics for Oswin
>   Storing new statistics for Florina
>   Storing new statistics for Wallace
>   Storing new statistics for Pent
>   Storing new statistics for Serra
>   Storing new statistics for Isadora
>   Storing new statistics for Erk
>   Storing new statistics for Heath
>   Storing new statistics for Nino
>   Storing new statistics for Rebecca
>   Storing new statistics for Wil
>   Storing new statistics for Hector
> All user stats updated for game #0
> Game saved with id 1.
> Database connection ended.

</details>

and `node server.js --no-github`

![image](https://user-images.githubusercontent.com/2547646/32149946-46027968-bd0c-11e7-8576-8374c6dd55d6.png)

**Comment by Asuza** [comment]
Thanks, @jeromechrist! It seems to work for me. I had to do steps a little bit differently than you'd written down, but this worked:

```bash
docker build -t ai-battle-website .
docker run -it -p 8080:8080 ai-battle-website
```
Then inside the docker container:
```bash
service postgresql start
# update config.js user to "vagrant"
node database/initialize.js
sudo su - postgres
cd /app
psql jsfightclub < ./node_modules/connect-pg-simple/table.sql
node gamerunner/run-test-game.js

npm run build
node server.js --no-github
```

Everything works great! The only reason your website didn't load properly in the screenshot you posted is because of the missing `npm run build` step.

But, I was able to run the uglify command without any problem, so I'm not sure why it didn't work for you? Regardless, I think this is ready to merge.

Should the database be in a different container than the application? I've heard that Docker should ideally run only one process per container, but I'm pretty new to Docker in general.

**Comment by Asuza** [comment]
Fixed via #69

**Comment by jeromechrist** [comment]
@Asuza 

Welp, glad it works for you.

I call `npm run build` inside the dockerfile, [see ](https://github.com/JSJitsu/ai-battle-website/blob/c63a22b837709eddab4d453294b45a31a0bc9175/Dockerfile#L45), so i don't have to run this cmd manually for every container.

I think it's some CRLF shenanigans since i cloned the repo on my Windows machine which is then copied inside the ubuntu image. I will test that this afternoon.

Yep the DB _should_ be in a different container, then you would use docker-compose to bring the website + the DB tier up&linked together, that depends if you want to use this docker image as the vagrant one (== as a dev container), _ideally_ you would devevelop on your local machine -or a docker container why not-, build on another container, and run it inside the docker-composed one with the tiers separated.

+ the manuals steps could be automated & integrated into the source so you don't have to manually specify a psql user.

if you want to go that route i'd be glad to help, hacktoberfest or not :-)

**Comment by Asuza** [comment]
That's fine if the container acts more like a dev container than a true Docker setup. I would like to improve the ease of getting up and running for contributors, so if the container can start the postgres service, like Vagrant does, that would simplify things a little bit. I'm hopeful that with #68, manual database setup will no longer be required.

I have no intentions (so far) to deploy Docker containers to production, so any changes made to it can be solely with ease of development in mind.

Thank you.
