### ISSUE TITLE
No battles since November 30th

### ISSUE THREAD

**Issue by dtfinch** [JSJitsu/ai-battle-website#71]
Just a heads up. There hasn't been a new battle set the last few days on the live website, judging by played_at on battle 1583.

**Comment by Asuza** [comment]
Thanks! I'll check it ASAP.

**Comment by Asuza** [comment]
Alright, the issue has been resolved, and I ran the missing game for today.

**Comment by dtfinch** [comment]
Now the API is always returning the latest game 1591.

![wronggame](https://user-images.githubusercontent.com/1477446/33530277-1ba50208-d832-11e7-8f1d-56f28ac0218f.png)

**Comment by Asuza** [comment]
That's concerning. I'll take a look shortly.

**Comment by Asuza** [comment]
Fixed that issue as well. Thanks!
