### ISSUE TITLE
Site layout for small screen sizes

### ISSUE THREAD

**Issue by DiscipleOfShinku** [JSJitsu/ai-battle-website#72]
Hello!

Site layout is not responsive, so on small screen sizes significant part of the screen is covered with the team red list and only left side of the battlefield is visible. Furthermore, horizontal scroll is unavailable.

**Comment by Asuza** [comment]
Thanks! The current site is a huge mess of old code. I'm working on a new version of the site which will hopefully be easier to make mobile-friendly.

**Comment by Asuza** [comment]
@DiscipleOfShinku, the site has finally been re-built and has become maintainable for the first time in... maybe ever. As long as you choose to "view desktop version" on mobile, it looks fine. I'll now be trying to incrementally improve the mobile version of the site as I have time.

If you want to take a stab at it, let me know (and look at the _riotjs_ branch, not _master_).

**Comment by DiscipleOfShinku** [comment]
Oh! I didn't know that such option exist in mobile browsers, not only on sites.

It would be interesting to give a try. What thoughts do you have about layout for mobile devices?

**Comment by Asuza** [comment]
Good question! I like to think I'm not too picky, but I'll try to give it some thought. I think the navigation and a visible battle grid would be most important.

FYI, if you give it a try too soon, the readme is a bit out of date at the moment.

**Comment by DiscipleOfShinku** [comment]
I think battlefield on mobile devices will look better with sprites with less padding and with vertical health bar instead of name. Or maybe sprites themselves could be health bars.
And here I think maybe tiles could be even clickable for stats view popup.

I'll wait updated readme.

**Comment by Asuza** [comment]
I updated the readme... I recommend using Docker, if possible. I've been using it for development for this for a little while now since Vagrant quit working on me, and it should be the smoothest to get going with.

Let me know if anything gives you trouble.

**Comment by DiscipleOfShinku** [comment]
I think contributing.md is outdated too, since it points out that I should branch from _master_.

**Comment by Asuza** [comment]
You should branch from _master_, I merged _riotjs_ into it since I made that comment. I should have mentioned that here.

Will vagrant work for you? I'm sure I can help you get the site working with it... I just can't use it personally to make it as easy as possible.

If not, you would need PostgreSQL 9.5 or higher and Node 6 or higher, and ideally yarn. Maybe you already have those things installed? If you have some other database service, you might be able to use it with some tweaking.

**Comment by DiscipleOfShinku** [comment]
Is it OK if I'll use `grid`? And probably stylus.

**Comment by DiscipleOfShinku** [comment]
Grid is [partially supported by IE 11 and not supported by Opera Mini and several minor browsers](https://caniuse.com/#search=grid) but supported by other major browsers.
Stylus is [CSS preprocessor](https://github.com/stylus/stylus/) which allows using of [simple media queries](https://github.com/jescalan/rupture) but requires compilation of .css files from .styl files.

**Comment by Asuza** [comment]
I've used some CSS preprocessors, but not that one! Feel free to use it. There's no real build process to speak of, so hopefully that doesn't get in your way too much. I still need to research how I'd like to handle that for building Riot.

**Comment by Asuza** [comment]
Thank you for this update! Fixed in #82.
