### ISSUE TITLE
Missing folder when build with docker

### ISSUE THREAD

**Issue by DiscipleOfShinku** [JSJitsu/ai-battle-website#76]
Running command
`docker build -t ai-battle-website .`
I've got this message:
> sh: 1: cannot create public/js/game-engine.js: Directory nonexistent
> ...
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     browserify ./node_modules/ai-battle-engine/index.js --standalone GameEngine > public/js/game-engine.js

Probably `mkdir public/js` is missing.

**Comment by Asuza** [comment]
@DiscipleOfShinku pull in master and try again. It should be fine now.
