### ISSUE TITLE
Errors when running ./docker-startup.sh

### ISSUE THREAD

**Issue by DiscipleOfShinku** [JSJitsu/ai-battle-website#78]
After running `./docker-startup.sh` I've got this output:

>  * Starting PostgreSQL 9.5 database server                                                                                                            [ OK ]
> yarn install v1.5.1
> [1/4] Resolving packages...
> success Already up-to-date.
> Done in 2.32s.
> yarn run v1.5.1
> $ npm run build-engine
> 
> > javascript-battle-website@1.0.0 build-engine /app
> > browserify ./node_modules/ai-battle-engine/index.js --standalone GameEngine > public/lib/game-engine.js
> 
> Done in 2.87s.
> Working directory changed to /app/database/config
> module.js:478
>     throw err;
>     ^
> 
> Error: Cannot find module '../../config'
>     at Function.Module._resolveFilename (module.js:476:15)
>     at Function.Module._load (module.js:424:25)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/app/database/config/knexfile.js:2:16)
>     at Module._compile (module.js:577:32)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at initKnex (/app/node_modules/knex/bin/cli.js:50:16)
>     at Command.<anonymous> (/app/node_modules/knex/bin/cli.js:127:17)
>     at Command.listener (/app/node_modules/knex/node_modules/commander/index.js:315:8)
>     at emitTwo (events.js:106:13)
> ERROR:  relation "session" already exists
> ERROR:  multiple primary keys for table "session" are not allowed
> module.js:478
>     throw err;
>     ^
> 
> Error: Cannot find module '../../config'
>     at Function.Module._resolveFilename (module.js:476:15)
>     at Function.Module._load (module.js:424:25)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/app/database/config/knexfile.js:2:16)
>     at Module._compile (module.js:577:32)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)
> module.js:478
>     throw err;
>     ^
> 
> Error: Cannot find module './config'
>     at Function.Module._resolveFilename (module.js:476:15)
>     at Function.Module._load (module.js:424:25)
>     at Module.require (module.js:504:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/app/server.js:7:16)
>     at Module._compile (module.js:577:32)
>     at Object.Module._extensions..js (module.js:586:10)
>     at Module.load (module.js:494:32)
>     at tryModuleLoad (module.js:453:12)
>     at Function.Module._load (module.js:445:3)

**Comment by Asuza** [comment]
Make a copy of the config template file and name it _config.js_. You might need to set the user for the database connection but most of the defaults should be okay, I think. I'll try to paste mine here when I can.

**Comment by Asuza** [comment]
Please re-open the issue if you're still having trouble.

**Comment by woprzech** [comment]
I created a copy of the config file and set user to 'user' but I still get an error:
```
error: password authentication failed for user "user"
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)

```

**Comment by woprzech** [comment]
Ok, I run /database/setup-postgres.sh with proper parameters for 'user' and it is working now :)

**Comment by Asuza** [comment]
Glad you figured it out! If you want to tweak some files or configs to make things easier for others, feel free.
