### ISSUE TITLE
Mines from previous games on battlefield

### ISSUE THREAD

**Issue by DiscipleOfShinku** [JSJitsu/ai-battle-website#79]
After site was updated to a new version I started to notice that when I select another game, mines from previous game remain on battlefield, messing with new tiles.

![mines](https://user-images.githubusercontent.com/23262724/38473042-a94205f8-3b91-11e8-9096-cb6b098c0246.png)

I observed that behavior in 3 major browsers.
I think that `<virtual>` component's content destroying may be bugged. I changed `battle.tag` template to not use `<virtual>` tag and it seems it's helped. Now I have to come up with good commit message.

**Comment by Asuza** [comment]
Thank you for looking into that! I wasn't sure what the issue was. I believed it was related to the Riot attribute `no-reorder`, which I had to use to keep performance reasonable. Removing that attribute seemed to resolve the issue, but using the slider becomes unbearably slow if you do. Either way, it feels like possibly a bug with Riot.

**Comment by DiscipleOfShinku** [comment]
I have some problem with branch updating (well, with pushing too, but I'll yet have to look into it):

> $ git pull upstream/master
> fatal: 'upstream/master' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> $ git remote -v
> origin  https://github.com/DiscipleOfShinku/ai-battle-website (fetch)
> origin  https://github.com/DiscipleOfShinku/ai-battle-website (push)
> upstream        https://github.com/JSJitsu/ai-battle-website.git (fetch)
> upstream        https://github.com/JSJitsu/ai-battle-website.git (push)

**Comment by DiscipleOfShinku** [comment]
Turns out it should be `git pull upstream master`, not `git pull upstream/master`. Probably a new version of interface.

**Comment by Asuza** [comment]
Fixed via #80. Thanks! It should now be live.
