### ISSUE TITLE
Switching tabs causes a script error

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-website#8]
The "tabs" under "Learn the Basics" and under your user options (at the bottom of the page) cause script errors when they are clicked.

**Comment by Asuza** [comment]
The "tabs" under "Learn the Basics" and under your user options (at the bottom of the page) cause script errors when they are clicked.

**Comment by natedsaint** [comment]
Same issue as the user dropdown: not broken in the built version. Use grunt watch to quickly build in dev to verify.
