### ISSUE TITLE
Partial battles today

### ISSUE THREAD

**Issue by dtfinch** [JSJitsu/ai-battle-website#83]
I noticed that only 4 battles appear for today, the 19th.

**Comment by Asuza** [comment]
Thanks, I'll look into this as soon as I can.

**Comment by Asuza** [comment]
It looks like the database ran out of connections or something along those lines. I've merged several changes today that will hopefully prevent that from happening for a while.

The changes include:
- Increasing the number of available database pools
- Temporarily disabling user accounts who don't have hero/helper code

If all goes well, the next battle will have fewer total games, but without anyone simply standing around.

**Comment by Asuza** [comment]
Seemed to work. Closing this ticket, but please open another if you spot anything suspicious.
