### ISSUE TITLE
Wrong recent stats

### ISSUE THREAD

**Issue by DiscipleOfShinku** [JSJitsu/ai-battle-website#89]
I'm getting wrong values for most of attributes in recent stats. From other game maybe (a team and a winner values do not correspond to those of my recent game)?
Also, I think my "recent" values did not change for some time.

**Comment by DiscipleOfShinku** [comment]
If that'll help, values I every time get are:

- kills: 4
- damage dealt: 210
- mine captured: 0
- diamonds earned: 0
- health recovered: 0
- souls absorbed: 2

**Comment by Asuza** [comment]
Thanks! I'm posting what I have for today and I'll try to check it again tomorrow:

- kills: 0
- damage dealt: 50
- mines captured: 0
- diamonds earned: 0
- health recovered: 0
- souls absorbed: 0

**Comment by Asuza** [comment]
This should be fixed now. There was some bad data in the _game_results_ table which has been removed. This might slightly alter lifetime stats for some players, but it shouldn't be a significant change.

**Comment by DiscipleOfShinku** [comment]
Yes, now stats seems to be correct. Thank you!
