### ISSUE TITLE
What Node.js version is being used to run the simulation?

### ISSUE THREAD

**Issue by flesler** [JSJitsu/ai-battle-website#96]
My bot is working perfectly locally with Node.js v8.11.3. The package.json doesn't specify any specific version or requirement by 8.x is the current LTS.

I tried an overhaul of my bot today and it didn't move, I'm guessing it's due to the Node.js version.

Can you confirm and, if you are using something like 6.x, considering switching to LTS?

Thanks

**Comment by Asuza** [comment]
The server is running Node 8, so that shouldn't be a problem for you. I'm seeing the following error in the logs:

```
        return arr.reduce((accum, val) => (
                   ^

TypeError: Cannot read property 'reduce' of undefined
    at sum (user_code/hero/
lesler_hero.js:41:13)
    at count (user_code/her
/flesler_hero.js:48:9)
    at countAround (user_co
e/hero/flesler_hero.js:73:9)
    at _ (user_code/hero/fl
sler_hero.js:132:7)
    at module.exports (user
code/hero/flesler_hero.js:192:16)
```

Let me know if that doesn't help and I'll see what I can do to assist.

**Comment by flesler** [comment]
Hi, thanks for providing the logs (and so fast!). I'm testing with the test_battle, will see if I figure out the issue

**Comment by flesler** [comment]
@Asuza seems like it's still broken. Do you mind posting updated logs? Thanks

**Comment by Asuza** [comment]
I don't see any errors in the logs for the past few days for your hero. I watched the [latest game with your hero in it](https://jsfight.club/#game/3468), and the database shows that it had 4 turns, but didn't perform a valid action during any of those turns.

The related queries, if you're interested:
```
jsfightclub=# select heroes from game where id=3468;
-[ RECORD 1 ]-------------------------------------------------
heroes | [..., {"id": 10, "name": "flesler", "team": 0}, ...]
```

```
jsfightclub=# select * from game_events where game_id=3468 and actor=10;
 game_id | turn | actor | action 
---------+------+-------+--------
    3468 |   72 |    10 | 
    3468 |   53 |    10 | 
    3468 |   32 |    10 | 
    3468 |   10 |    10 | 
(4 rows)
```
If you want to add `console` output to your hero, that will show up in the logs and I can send it to you after the next game runs.

**Comment by flesler** [comment]
I still don't figure out what, but something works differently when running the test_battle and the real thing, I wonder what is it. But yes, the last match was not a good one to measure because it died quickly and started quite cornered. I might add logs, will also check tomorrow's match and get back to you.

Thanks @Asuza

**Comment by Asuza** [comment]
If you do add logs, please add some identifier to the start of each one, like "`[flesler]`". Otherwise, I can't tell your logs apart from anyone else's.

**Comment by dtfinch** [comment]
I think the difference here is that the website battle converts the gamedata object to json and back, which break all the shared references (like myHero vs its tile) into separate copies.

**Comment by flesler** [comment]
@Asuza I've been checking the game runner in this project and the script that fetches code. I don't see anything out of the ordinary.

My guess is the `gameData` object is different when running for real and in the test.

I see there's a [run-test-game.js](https://github.com/JSJitsu/ai-battle-website/blob/master/gamerunner/run-test-game.js), I don't have a DB with the GH auth keys (obviously). Could you maybe run that but switching one of the users to `'flesler'`?

**Comment by flesler** [comment]
@dtfinch my code at least is copying all the data to the outer scope every time the "move function" is called, that should keep the references up to date no?

**Comment by dtfinch** [comment]
When you modify the tiles to add .x, .y, and such, game.activeHero/myHero is unaffected because it's not pointing to the tile, but rather a copy due to the json encode/decode.

**Comment by flesler** [comment]
@dtfinch ohhh I get it now. That makes sense, will patch that and see if that solves it

**Comment by flesler** [comment]
Ok done, let's see if it works tonight

**Comment by flesler** [comment]
Ok it worked now, thanks a lot to both
