### ISSUE TITLE
Allow speeding up battles

### ISSUE THREAD

**Issue by flesler** [JSJitsu/ai-battle-website#97]
Maybe a thing you click and it goes 2x -> 4x -> 1x

It might be cool to speed up all moves except the one from the signed user

**Comment by redice44** [comment]
I'll take a run at this. I think the only thing I'm a bit concerned about is slowing it down to `1x` speed for the signed in user's turn. If it's just a straight speed up that shouldn't be much of a problem. 

Thoughts on just making it a straight speed up across the board? @Asuza

**Comment by Asuza** [comment]
@redice44, it should speed up the speed of the entire game via a select box or some other UI component... I'm fine with it being for all turns of the game.

If you *want* to, you could add a checkbox to slow down the speed for the person logged in, but it's not necessary by any means.

**Comment by redice44** [comment]
@Asuza PR is up for this issue 😄  Please take a look and let me know what you think. Enjoying this project. Nice job 👍

**Comment by Asuza** [comment]
Thanks for the PR, @redice44! It looked good to me, and the changes are now live. Closed via #101.
